#!/usr/bin/env python3
"""Build a SEPARATE world in which the ten apples genuinely differ in fragility.

In the normal world every apple has the same contact softness and colour, so fragility is
not a property of anything: a vision model or a finger sensor has nothing real to detect,
and there is nothing to score an estimate against. This writes, without touching the
normal world or the normal apple models:

  src/apple_gripper_sim/models/fragile_apple_XX/     copies of each apple with
        contact stiffness (kp) and colour set from a fragility score
  src/apple_gripper_sim/worlds/apple_world_fragility.world
        the normal world, including those copies under the SAME names (apple_01 ...),
        so every topic, pose bridge and script works unchanged
  src/apple_gripper_sim/fragility_truth.json
        the true fragility per apple -- read only when SCORING estimates, never when
        choosing a grip

Fragility is assigned in an order unrelated to size (sizes rise with the apple number), so
an estimator cannot get fragility right just by looking at how big an apple is.

Softer = lower contact stiffness kp, spaced evenly on a log scale from 1e6 (firm) to 1e3
(very soft), and colour moving from firm green-red through ripe red to overripe brown.
Whether the physics engine actually honours kp is NOT assumed: the first logged run in
this world measures it (see fit_touch_calibration.py).

Usage (from the repository root):
    python3 tools/make_fragility_world.py
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIM = os.path.join(ROOT, "src", "apple_gripper_sim")
MODELS = os.path.join(SIM, "models")
WORLDS = os.path.join(SIM, "worlds")

# True fragility per apple (0 = very firm, 10 = very fragile). Deliberately not ordered by
# apple number, which is also size order.
FRAGILITY = {"apple_01": 7, "apple_02": 2, "apple_03": 9, "apple_04": 4, "apple_05": 1,
             "apple_06": 6, "apple_07": 3, "apple_08": 8, "apple_09": 5, "apple_10": 0}

KP_FIRM, KP_SOFT = 1.0e6, 1.0e3

FIRM_RGB = (0.55, 0.62, 0.20)      # hard, under-ripe
RIPE_RGB = (0.77, 0.12, 0.16)      # the colour every apple has in the normal world
SOFT_RGB = (0.36, 0.14, 0.08)      # overripe, bruised brown


def kp_for(f):
    # log-spaced: fragility 0 -> KP_FIRM, 10 -> KP_SOFT
    return KP_FIRM * (KP_SOFT / KP_FIRM) ** (f / 10.0)


def colour_for(f):
    if f <= 5:
        t, a, b = f / 5.0, FIRM_RGB, RIPE_RGB
    else:
        t, a, b = (f - 5) / 5.0, RIPE_RGB, SOFT_RGB
    return tuple(round(a[i] + (b[i] - a[i]) * t, 3) for i in range(3))


def build_model(name, f):
    src_dir = os.path.join(MODELS, name)
    dst_name = f"fragile_{name}"
    dst_dir = os.path.join(MODELS, dst_name)
    os.makedirs(dst_dir, exist_ok=True)

    sdf = open(os.path.join(src_dir, "model.sdf"), encoding="utf-8").read()
    n_kp = len(re.findall(r"<kp>[^<]*</kp>", sdf))
    if n_kp == 0:
        raise RuntimeError(f"{name}: no <kp> found to set")
    kp = kp_for(f)
    sdf = re.sub(r"<kp>[^<]*</kp>", f"<kp>{kp:.1f}</kp>", sdf)
    r, g, b = colour_for(f)
    rgba = f"{r} {g} {b} 1"
    sdf = re.sub(r"<ambient>[^<]*</ambient>", f"<ambient>{rgba}</ambient>", sdf)
    sdf = re.sub(r"<diffuse>[^<]*</diffuse>", f"<diffuse>{rgba}</diffuse>", sdf)
    sdf = sdf.replace(f'<model name="{name}">', f'<model name="{dst_name}">', 1)
    # No "--" anywhere inside these comments: XML forbids it within a comment.
    header = (f"<!-- GENERATED by tools/make_fragility_world.py; do not edit by hand.\n"
              f"     Fragility {f}/10: contact stiffness kp={kp:.1f}, colour {rgba}.\n"
              f"     Everything else (size, mass, friction, flat base, mesh) is the normal\n"
              f"     {name}. -->\n")
    sdf = sdf.replace("<sdf ", header + "<sdf ", 1)
    with open(os.path.join(dst_dir, "model.sdf"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(sdf)

    cfg = open(os.path.join(src_dir, "model.config"), encoding="utf-8").read()
    cfg = cfg.replace(f"<name>{name}</name>", f"<name>{dst_name}</name>", 1)
    cfg = re.sub(r"<description>[^<]*</description>",
                 f"<description>{name} with fragility {f}/10 (generated)</description>", cfg)
    with open(os.path.join(dst_dir, "model.config"), "w", encoding="utf-8",
              newline="\n") as fh:
        fh.write(cfg)
    return {"fragility": f, "kp": round(kp, 1), "rgba": [r, g, b, 1],
            "model": dst_name, "kp_blocks": n_kp}


def main():
    truth = {}
    for name, f in sorted(FRAGILITY.items()):
        truth[name] = build_model(name, f)

    world = open(os.path.join(WORLDS, "apple_world.world"), encoding="utf-8").read()
    for name in FRAGILITY:
        old = f"<uri>model://{name}</uri>"
        if world.count(old) != 1:
            raise RuntimeError(f"expected exactly one include of {name} in apple_world.world")
        world = world.replace(old, f"<uri>model://fragile_{name}</uri>")
    world = world.replace(
        "<sdf ",
        "<!-- GENERATED by tools/make_fragility_world.py from apple_world.world, identical\n"
        "     except that each apple is its fragile_apple_XX copy, still named apple_XX. -->\n"
        "<sdf ", 1)
    out_world = os.path.join(WORLDS, "apple_world_fragility.world")
    with open(out_world, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(world)

    out_truth = os.path.join(SIM, "fragility_truth.json")
    with open(out_truth, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(truth, fh, indent=2)

    print(f"wrote {out_world}")
    print(f"wrote {out_truth}")
    for name in sorted(truth):
        t = truth[name]
        print(f"  {name}: fragility {t['fragility']:>2}  kp {t['kp']:>10.1f}  rgba {t['rgba']}")


if __name__ == "__main__":
    main()
